Sprint 1/step 2
Mir0van/react-burger pull request #1
Opened 2024-05-26 02:41 UTC by Mir0van

2024-05-26 07:30 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-05-26 07:30 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      {visible === 'orderDetails' &&
**Надо исправить:**

здесь и в похожих местах.

Тут лучше использовать boolean переменную, а не значение

2024-05-28 10:19 UTC, Mir0van commented
Привет, спасибо! Я правильно понял как нужно запрос на сервер вынести и модалку?

2024-05-28 13:12 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-05-28 13:12 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +      .then(data => {
**Можно лучше:**

тут можно деструктурировать) - `({data}) => { setIngredientsData(data) }`

2024-05-28 13:12 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          onClose={() => setIsOrderModalOpen(false)}
**Можно лучше:**

лучше вынести обработчик события в отдельную функцию.

2024-05-28 13:12 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
> +  return selectedIngredient && (
**Можно лучше:**

по идее эта проверка не нужна вообще) так что её можно убрать. 
На будущее, лучше всегда стараться ставить условия от противного: 

```js
if(!selectedIngredient) return null;

return ( ... )
```

Да, это чуть больше по коду, но плюс в том, что у вас практически не будет вложенных условий (в том случае когда условий больше 1 и они идут последовательно). 

Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2024-05-28 13:13 UTC, ArslanMustafin commented
> Привет, спасибо! Я правильно понял как нужно запрос на сервер вынести и модалку? Еще поменял логику обработки пропса ingredientsData в BurgerIngredients до этого я записывал в useState через useEffect как только придет не пустой массив, а теперь через useMemo. такой подход более правильный, я правильно понял?

Привет, да всё правильно понял))

2024-05-29 09:12 UTC, Mir0van commented on src/components/burger-ingredients/burger-ingredients.jsx
>            ))}
Спасибо! я в начале примерно так и сделал, но потом подумал сделать так, что бы учитывалось вдруг появились бы другие категории) но если будут в дальнейшем сложности с моим кодом то вернусь к такой версии

2024-05-29 09:45 UTC, merged